# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
gravatar: https://avatars1.githubusercontent.com/u/1656327?v=3&s=460

nav:
  archive: /archive
  about: /about
  tags: /tags

# Social
# social:
# - github: 
# - dribbble: 
# - weibo: 
# - wechat: 
# - rss: 

social:
  github: http://github.com/codersir
  dribbble: 
  weibo: 
  wechat: 
  rss: 

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: