# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
gravatar: /image/site/gravatar.png

nav:
  Archives: /archives
  Resume: /resume
  Tags: /tags

social:
  github: http://github.com/xuhong
  dribbble:
  weibo:
  # wechat: HUSTecho
  instagram: http://instagram.com/codersir
  rss: /atom.xml

# Miscellaneous
disqus_shortname: codersirblog
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
